import type { Order } from "@/types";

// Helper: dates relative to today (Feb 19, 2026)
const today = new Date("2026-02-19");
function daysFromToday(days: number): string {
  const d = new Date(today);
  d.setDate(d.getDate() + days);
  return d.toISOString().split("T")[0];
}
function daysAgo(days: number): string {
  return daysFromToday(-days);
}
function isoTs(dateStr: string, time = "10:00:00"): string {
  return `${dateStr}T${time}.000Z`;
}

export const mockOrders: Order[] = [
  // ── 1. OVERDUE — Building stage, delivery was 5 days ago ──────────────────
  {
    id: "ord-001",
    type: "order",
    orderNumber: "EVL-2026-001",
    shareableToken: "evl-001-priya-ring",
    customerName: "Priya Mehta",
    customerPhone: "+91 98200 11234",
    customerEmail: "priya.mehta@gmail.com",
    customerAddress: "14, Juhu Scheme, Mumbai 400049",
    salespersonName: "Ananya S.",
    vendorName: "Raj Jewel Craft",
    category: "Ring",
    metalType: "Gold",
    metalPurity: "18K",
    metalWeight: 4.2,
    polish: "High polish",
    stoneDescription: "Natural Diamonds",
    stoneQuality: "VS2",
    stoneCut: "Round Brilliant",
    stoneCaratEstimate: 0.5,
    ringSize: "13",
    certification: "GIA",
    cadDesignRequired: true,
    advancePaid: 25000,
    totalEstimate: 85000,
    deliveryDate: daysFromToday(-5),
    currentStage: "Building",
    createdAt: isoTs(daysAgo(30)),
    lastUpdatedAt: isoTs(daysAgo(4)),
    activityFeed: [
      {
        id: "act-001-1",
        orderId: "ord-001",
        postedBy: "Ananya S.",
        timestamp: isoTs(daysAgo(30)),
        type: "stage_change",
        newStage: "Order Confirmed",
        note: "Order confirmed. Advance of ₹25,000 received. Sent to Raj Jewel Craft.",
      },
      {
        id: "act-001-2",
        orderId: "ord-001",
        postedBy: "Ananya S.",
        timestamp: isoTs(daysAgo(28)),
        type: "stage_change",
        newStage: "CAD Design",
        note: "CAD design phase started.",
      },
      {
        id: "act-001-3",
        orderId: "ord-001",
        postedBy: "Raj Jewel Craft",
        timestamp: isoTs(daysAgo(24)),
        type: "file_upload",
        note: "CAD design ready for approval.",
        file: {
          url: "/mock/cad-evl001.pdf",
          filename: "EVL-001-CAD-v1.pdf",
          fileType: "pdf",
        },
      },
      {
        id: "act-001-4",
        orderId: "ord-001",
        postedBy: "Ananya S.",
        timestamp: isoTs(daysAgo(22)),
        type: "stage_change",
        newStage: "Building",
        note: "CAD approved by customer. Proceeding to build.",
      },
      {
        id: "act-001-5",
        orderId: "ord-001",
        postedBy: "Raj Jewel Craft",
        timestamp: isoTs(daysAgo(4)),
        type: "note",
        note: "Stone setting in progress. Slight delay due to stone sourcing. Will update by end of week.",
      },
    ],
    specialInstructions:
      "Customer wants engraving inside band: 'P & R 14.02.2025'",
  },

  // ── 2. DUE SOON (3 days) — Certification stage ────────────────────────────
  {
    id: "ord-002",
    type: "order",
    orderNumber: "EVL-2026-002",
    shareableToken: "evl-002-arjun-necklace",
    customerName: "Arjun Kapoor",
    customerPhone: "+91 99870 55678",
    customerEmail: "arjun.kapoor@outlook.com",
    customerAddress: "8, Bandra West, Mumbai 400050",
    salespersonName: "Dev R.",
    vendorName: "Sunrise Gold Works",
    category: "Necklace",
    metalType: "Gold",
    metalPurity: "22K",
    metalWeight: 18.5,
    polish: "Matte",
    stoneDescription: "Uncut Polki Diamonds",
    stoneQuality: "AAA Grade",
    stoneCut: "Polki",
    certification: "IGI",
    cadDesignRequired: false,
    advancePaid: 60000,
    totalEstimate: 210000,
    deliveryDate: daysFromToday(3),
    currentStage: "Certification",
    createdAt: isoTs(daysAgo(45)),
    lastUpdatedAt: isoTs(daysAgo(2)),
    activityFeed: [
      {
        id: "act-002-1",
        orderId: "ord-002",
        postedBy: "Dev R.",
        timestamp: isoTs(daysAgo(45)),
        type: "stage_change",
        newStage: "Order Confirmed",
        note: "Anniversary necklace order confirmed. Delivery needed by end of month.",
      },
      {
        id: "act-002-2",
        orderId: "ord-002",
        postedBy: "Sunrise Gold Works",
        timestamp: isoTs(daysAgo(20)),
        type: "stage_change",
        newStage: "Building",
        note: "Started crafting. All materials procured.",
      },
      {
        id: "act-002-3",
        orderId: "ord-002",
        postedBy: "Sunrise Gold Works",
        timestamp: isoTs(daysAgo(7)),
        type: "stage_change",
        newStage: "Certification",
        note: "Piece completed and dispatched to IGI lab for certification.",
      },
      {
        id: "act-002-4",
        orderId: "ord-002",
        postedBy: "Dev R.",
        timestamp: isoTs(daysAgo(2)),
        type: "note",
        note: "Checked with IGI. Certificate will be ready in 2 days.",
      },
    ],
  },

  // ── 3. DUE SOON (6 days) — Shipped to Store ──────────────────────────────
  {
    id: "ord-003",
    type: "order",
    orderNumber: "EVL-2026-003",
    shareableToken: "evl-003-deepa-bangles",
    customerName: "Deepa Nair",
    customerPhone: "+91 91234 77890",
    salespersonName: "Ananya S.",
    vendorName: "Heritage Crafts Mumbai",
    category: "Bangle",
    metalType: "Gold",
    metalPurity: "22K",
    metalWeight: 42,
    polish: "High polish",
    stoneDescription: "Ruby and Emerald",
    stoneQuality: "Good",
    stoneCut: "Cabochon",
    bangleSize: "2.6 inches",
    certification: "Jewellery",
    cadDesignRequired: false,
    advancePaid: 80000,
    totalEstimate: 310000,
    deliveryDate: daysFromToday(6),
    currentStage: "Shipped to Store",
    createdAt: isoTs(daysAgo(60)),
    lastUpdatedAt: isoTs(daysAgo(1)),
    activityFeed: [
      {
        id: "act-003-1",
        orderId: "ord-003",
        postedBy: "Ananya S.",
        timestamp: isoTs(daysAgo(60)),
        type: "stage_change",
        newStage: "Order Confirmed",
        note: "Bridal bangles set — 2 pairs. Order confirmed with Heritage Crafts.",
      },
      {
        id: "act-003-2",
        orderId: "ord-003",
        postedBy: "Heritage Crafts Mumbai",
        timestamp: isoTs(daysAgo(30)),
        type: "stage_change",
        newStage: "Building",
        note: "Work has begun on the bangles set.",
      },
      {
        id: "act-003-3",
        orderId: "ord-003",
        postedBy: "Heritage Crafts Mumbai",
        timestamp: isoTs(daysAgo(10)),
        type: "file_upload",
        note: "Progress photo — stone setting complete.",
        file: {
          url: "/mock/bangles-progress.jpg",
          filename: "bangles-progress-photo.jpg",
          fileType: "image",
        },
      },
      {
        id: "act-003-4",
        orderId: "ord-003",
        postedBy: "Heritage Crafts Mumbai",
        timestamp: isoTs(daysAgo(3)),
        type: "stage_change",
        newStage: "Certification",
        note: "Sent for hallmarking.",
      },
      {
        id: "act-003-5",
        orderId: "ord-003",
        postedBy: "Heritage Crafts Mumbai",
        timestamp: isoTs(daysAgo(1)),
        type: "stage_change",
        newStage: "Shipped to Store",
        note: "Shipped via Blue Dart. Tracking: BD-9821001234. Expected delivery to store: 2 days.",
      },
    ],
    specialInstructions:
      "Bridal set — handle with extra care. Customer picking up in person.",
  },

  // ── 4. ON TRACK — Building stage, delivery 15 days away ──────────────────
  {
    id: "ord-004",
    type: "order",
    orderNumber: "EVL-2026-004",
    shareableToken: "evl-004-rahul-pendant",
    customerName: "Rahul Singhania",
    customerPhone: "+91 88001 44321",
    salespersonName: "Dev R.",
    vendorName: "Raj Jewel Craft",
    category: "Pendant",
    metalType: "White Gold",
    metalPurity: "18K",
    metalWeight: 3.1,
    polish: "High polish",
    stoneDescription: "Blue Sapphire",
    stoneQuality: "Eye-clean",
    stoneCut: "Oval",
    stoneCaratEstimate: 1.2,
    certification: "SGL",
    cadDesignRequired: true,
    advancePaid: 15000,
    totalEstimate: 55000,
    deliveryDate: daysFromToday(15),
    currentStage: "Building",
    createdAt: isoTs(daysAgo(20)),
    lastUpdatedAt: isoTs(daysAgo(3)),
    activityFeed: [
      {
        id: "act-004-1",
        orderId: "ord-004",
        postedBy: "Dev R.",
        timestamp: isoTs(daysAgo(20)),
        type: "stage_change",
        newStage: "Order Confirmed",
        note: "Sapphire pendant — gift for wife's birthday.",
      },
      {
        id: "act-004-2",
        orderId: "ord-004",
        postedBy: "Dev R.",
        timestamp: isoTs(daysAgo(18)),
        type: "stage_change",
        newStage: "CAD Design",
        note: "Sent design brief to Raj Jewel Craft.",
      },
      {
        id: "act-004-3",
        orderId: "ord-004",
        postedBy: "Raj Jewel Craft",
        timestamp: isoTs(daysAgo(12)),
        type: "file_upload",
        note: "CAD design attached. Please review.",
        file: {
          url: "/mock/cad-evl004.pdf",
          filename: "EVL-004-sapphire-pendant-CAD.pdf",
          fileType: "pdf",
        },
      },
      {
        id: "act-004-4",
        orderId: "ord-004",
        postedBy: "Dev R.",
        timestamp: isoTs(daysAgo(10)),
        type: "stage_change",
        newStage: "Building",
        note: "Design approved. Proceeding to manufacture.",
      },
      {
        id: "act-004-5",
        orderId: "ord-004",
        postedBy: "Raj Jewel Craft",
        timestamp: isoTs(daysAgo(3)),
        type: "note",
        note: "Sapphire sourced and verified. Setting work starts Monday.",
      },
    ],
  },

  // ── 5. ON TRACK — Estimation stage ───────────────────────────────────────
  {
    id: "ord-005",
    type: "order",
    orderNumber: "EVL-2026-005",
    shareableToken: "evl-005-sunita-earrings",
    customerName: "Sunita Bose",
    customerPhone: "+91 97654 32100",
    customerEmail: "sunita.bose@yahoo.com",
    salespersonName: "Ananya S.",
    vendorName: "Sunrise Gold Works",
    category: "Earrings",
    metalType: "Gold",
    metalPurity: "18K",
    metalWeight: 5.8,
    polish: "High polish",
    stoneDescription: "Pink Tourmaline",
    stoneQuality: "VVS",
    stoneCut: "Pear",
    certification: "None",
    cadDesignRequired: false,
    advancePaid: 10000,
    totalEstimate: 38000,
    deliveryDate: daysFromToday(25),
    currentStage: "Estimation",
    createdAt: isoTs(daysAgo(5)),
    lastUpdatedAt: isoTs(daysAgo(1)),
    activityFeed: [
      {
        id: "act-005-1",
        orderId: "ord-005",
        postedBy: "Ananya S.",
        timestamp: isoTs(daysAgo(5)),
        type: "stage_change",
        newStage: "Order Confirmed",
        note: "Drop earrings — tourmaline. Customer wants these for a gala next month.",
      },
      {
        id: "act-005-2",
        orderId: "ord-005",
        postedBy: "Ananya S.",
        timestamp: isoTs(daysAgo(4)),
        type: "stage_change",
        newStage: "Estimation",
        note: "Sent specs to Sunrise Gold Works for quote.",
      },
      {
        id: "act-005-3",
        orderId: "ord-005",
        postedBy: "Sunrise Gold Works",
        timestamp: isoTs(daysAgo(1)),
        type: "note",
        note: "Reviewing stone availability. Will confirm estimate by tomorrow.",
      },
    ],
  },

  // ── 6. ON TRACK — Order Confirmed ─────────────────────────────────────────
  {
    id: "ord-006",
    type: "order",
    orderNumber: "EVL-2026-006",
    shareableToken: "evl-006-vijay-bracelet",
    customerName: "Vijay Tiwari",
    customerPhone: "+91 70000 99887",
    salespersonName: "Dev R.",
    vendorName: "Heritage Crafts Mumbai",
    category: "Bracelet",
    metalType: "Rose Gold",
    metalPurity: "18K",
    metalWeight: 8,
    polish: "Satin",
    stoneDescription: "Diamond tennis bracelet",
    stoneQuality: "SI1",
    stoneCut: "Round Brilliant",
    stoneCaratEstimate: 2.5,
    certification: "GIA",
    cadDesignRequired: false,
    advancePaid: 50000,
    totalEstimate: 175000,
    deliveryDate: daysFromToday(35),
    currentStage: "Order Confirmed",
    createdAt: isoTs(daysAgo(3)),
    lastUpdatedAt: isoTs(daysAgo(3)),
    activityFeed: [
      {
        id: "act-006-1",
        orderId: "ord-006",
        postedBy: "Dev R.",
        timestamp: isoTs(daysAgo(3)),
        type: "stage_change",
        newStage: "Order Confirmed",
        note: "Diamond tennis bracelet confirmed. Advance of ₹50,000 collected. Sent to Heritage Crafts.",
      },
    ],
    specialInstructions:
      "GIA cert mandatory before delivery. Customer will not accept without it.",
  },

  // ── 7. ENQUIRY — No delivery date, in Enquiry stage ──────────────────────
  {
    id: "enq-001",
    type: "enquiry",
    shareableToken: "enq-001-meera-chain",
    customerName: "Meera Pillai",
    customerPhone: "+91 94500 66123",
    salespersonName: "Ananya S.",
    category: "Chain",
    metalType: "Gold",
    metalPurity: "22K",
    polish: "High polish",
    certification: "None",
    cadDesignRequired: false,
    currentStage: "Enquiry",
    createdAt: isoTs(daysAgo(2)),
    lastUpdatedAt: isoTs(daysAgo(2)),
    budgetRange: "₹30,000 – ₹50,000",
    occasion: "Wedding gift",
    timelineNotes: "Needed within 3 weeks",
    activityFeed: [
      {
        id: "act-enq001-1",
        orderId: "enq-001",
        postedBy: "Ananya S.",
        timestamp: isoTs(daysAgo(2)),
        type: "stage_change",
        newStage: "Enquiry",
        note: "Walk-in enquiry. Customer interested in 22K gold chain, ~50–60cm. Budget around ₹40K.",
      },
    ],
  },

  // ── 8. COMPLETED — Customer Pickup ────────────────────────────────────────
  {
    id: "ord-007",
    type: "order",
    orderNumber: "EVL-2026-007",
    shareableToken: "evl-007-kavita-brooch",
    customerName: "Kavita Sharma",
    customerPhone: "+91 98100 77654",
    salespersonName: "Dev R.",
    vendorName: "Sunrise Gold Works",
    category: "Brooch",
    metalType: "Gold",
    metalPurity: "18K",
    metalWeight: 6.5,
    polish: "High polish",
    stoneDescription: "Emerald and Diamond",
    stoneQuality: "VS1",
    stoneCut: "Marquise",
    certification: "IGI",
    cadDesignRequired: false,
    advancePaid: 30000,
    totalEstimate: 95000,
    deliveryDate: daysFromToday(-10),
    currentStage: "Customer Pickup",
    createdAt: isoTs(daysAgo(50)),
    lastUpdatedAt: isoTs(daysAgo(10)),
    activityFeed: [
      {
        id: "act-007-1",
        orderId: "ord-007",
        postedBy: "Dev R.",
        timestamp: isoTs(daysAgo(50)),
        type: "stage_change",
        newStage: "Order Confirmed",
        note: "Antique-style brooch order confirmed.",
      },
      {
        id: "act-007-2",
        orderId: "ord-007",
        postedBy: "Sunrise Gold Works",
        timestamp: isoTs(daysAgo(25)),
        type: "stage_change",
        newStage: "Building",
        note: "Started crafting.",
      },
      {
        id: "act-007-3",
        orderId: "ord-007",
        postedBy: "Sunrise Gold Works",
        timestamp: isoTs(daysAgo(15)),
        type: "stage_change",
        newStage: "Certification",
        note: "Sent to IGI for certification.",
      },
      {
        id: "act-007-4",
        orderId: "ord-007",
        postedBy: "Sunrise Gold Works",
        timestamp: isoTs(daysAgo(12)),
        type: "stage_change",
        newStage: "Shipped to Store",
        note: "IGI certificate received. Piece shipped to store.",
      },
      {
        id: "act-007-5",
        orderId: "ord-007",
        postedBy: "Dev R.",
        timestamp: isoTs(daysAgo(10)),
        type: "stage_change",
        newStage: "Customer Pickup",
        note: "Kavita collected the piece. Full payment received. Order complete.",
      },
    ],
  },
];

// ─── Lookup helpers ────────────────────────────────────────────────────────────

export function getOrderById(id: string): Order | undefined {
  return mockOrders.find((o) => o.id === id);
}

export function getOrderByToken(token: string): Order | undefined {
  return mockOrders.find((o) => o.shareableToken === token);
}
