import type { Order } from "@/types";

// Helper: dates relative to today (Feb 19, 2026)
const today = new Date("2026-02-19");
function daysFromToday(days: number): string {
  const d = new Date(today);
  d.setDate(d.getDate() + days);
  return d.toISOString().split("T")[0];
}
function daysAgo(days: number): string {
  return daysFromToday(-days);
}
function isoTs(dateStr: string, time = "10:00:00"): string {
  return `${dateStr}T${time}.000Z`;
}

export const mockOrders: Order[] = [
  // ── 1. OVERDUE — Building stage, delivery was 5 days ago ──────────────────
  {
    id: "ord-001",
    type: "order",
    orderNumber: "EVL-2026-001",
    shareableToken: "evl-001-priya-ring",
    customerName: "Priya Mehta",
    customerPhone: "+91 98200 11234",
    customerEmail: "priya.mehta@gmail.com",
    customerAddress: "14, Juhu Scheme, Mumbai 400049",
    salespersonName: "Ananya S.",
    vendorName: "Raj Jewel Craft",
    category: "Ring",
    metalType: "Gold",
    metalPurity: "18K",
    metalWeight: 4.2,
    polish: "High polish",
    stoneDescription: "Natural Diamonds",
    stoneQuality: "VS2",
    stoneCut: "Round Brilliant",
    stoneCaratEstimate: 0.5,
    ringSize: "13",
    certification: "GIA",
    cadDesignRequired: true,
    advancePaid: 25000,
    totalEstimate: 85000,
    deliveryDate: daysFromToday(-5),
    currentStage: "Building",
    createdAt: isoTs(daysAgo(30)),
    lastUpdatedAt: isoTs(daysAgo(4)),
    specialInstructions: "Engrave 'P & R 14.02.2025' inside the band",
    activityFeed: [
      {
        id: "act-001-0",
        orderId: "ord-001",
        postedBy: "Ananya S.",
        actorRole: "sales",
        timestamp: isoTs(daysAgo(30), "09:15:00"),
        type: "order_created",
        note:
          "Order created. Advance of ₹25,000 received. Committed delivery by " +
          daysFromToday(-5) +
          ".",
      },
      {
        id: "act-001-1",
        orderId: "ord-001",
        postedBy: "Ananya S.",
        actorRole: "sales",
        timestamp: isoTs(daysAgo(30), "09:20:00"),
        type: "stage_change",
        previousStage: "Enquiry",
        newStage: "Order Confirmed",
        note: "Specs confirmed with customer. Sent full brief to Raj Jewel Craft over WhatsApp.",
      },
      {
        id: "act-001-2",
        orderId: "ord-001",
        postedBy: "Ananya S.",
        actorRole: "sales",
        timestamp: isoTs(daysAgo(28), "11:00:00"),
        type: "stage_change",
        previousStage: "Order Confirmed",
        newStage: "CAD Design",
        note: "CAD design phase kicked off with Raj Jewel Craft.",
      },
      {
        id: "act-001-3",
        orderId: "ord-001",
        postedBy: "Raj Jewel Craft",
        actorRole: "vendor",
        timestamp: isoTs(daysAgo(24), "16:30:00"),
        type: "file_upload",
        note: "First CAD draft ready. Please review with the customer and confirm before we proceed to casting.",
        file: {
          url: "/mock/cad-evl001.pdf",
          filename: "EVL-001-CAD-v1.pdf",
          fileType: "pdf",
        },
      },
      {
        id: "act-001-4",
        orderId: "ord-001",
        postedBy: "Priya Mehta",
        actorRole: "customer",
        timestamp: isoTs(daysAgo(23), "10:05:00"),
        type: "note",
        note: "Looks great! One small change — can the band be slightly wider? Around 3mm instead of 2.5mm.",
      },
      {
        id: "act-001-5",
        orderId: "ord-001",
        postedBy: "Raj Jewel Craft",
        actorRole: "vendor",
        timestamp: isoTs(daysAgo(23), "14:00:00"),
        type: "note",
        note: "Noted, updating the CAD. Will share revised version tomorrow.",
      },
      {
        id: "act-001-6",
        orderId: "ord-001",
        postedBy: "Raj Jewel Craft",
        actorRole: "vendor",
        timestamp: isoTs(daysAgo(22), "10:00:00"),
        type: "file_upload",
        note: "Revised CAD with 3mm band width. Ready for final approval.",
        file: {
          url: "/mock/cad-evl001-v2.pdf",
          filename: "EVL-001-CAD-v2.pdf",
          fileType: "pdf",
        },
      },
      {
        id: "act-001-7",
        orderId: "ord-001",
        postedBy: "Ananya S.",
        actorRole: "sales",
        timestamp: isoTs(daysAgo(22), "11:30:00"),
        type: "stage_change",
        previousStage: "CAD Design",
        newStage: "Building",
        note: "Customer approved the revised CAD. Proceeding to casting.",
      },
      {
        id: "act-001-8",
        orderId: "ord-001",
        postedBy: "Raj Jewel Craft",
        actorRole: "vendor",
        timestamp: isoTs(daysAgo(4), "15:00:00"),
        type: "note",
        note: "Stone setting in progress. Hit a snag — the VS2 round brilliants we sourced had an inclusions issue. Returning the batch and sourcing fresh stock. Estimated 5–6 more days. Apologies for the delay.",
      },
      {
        id: "act-001-9",
        orderId: "ord-001",
        postedBy: "Ananya S.",
        actorRole: "sales",
        timestamp: isoTs(daysAgo(3), "10:00:00"),
        type: "note",
        note: "Informed Priya about the delay. She's okay with waiting a few more days but needs it before the 28th at the latest.",
      },
    ],
  },

  // ── 2. DUE SOON (3 days) — Certification ──────────────────────────────────
  {
    id: "ord-002",
    type: "order",
    orderNumber: "EVL-2026-002",
    shareableToken: "evl-002-arjun-necklace",
    customerName: "Arjun Kapoor",
    customerPhone: "+91 99870 55678",
    customerEmail: "arjun.kapoor@outlook.com",
    customerAddress: "8, Bandra West, Mumbai 400050",
    salespersonName: "Dev R.",
    vendorName: "Sunrise Gold Works",
    category: "Necklace",
    metalType: "Gold",
    metalPurity: "22K",
    metalWeight: 18.5,
    polish: "Matte",
    stoneDescription: "Uncut Polki Diamonds",
    stoneQuality: "AAA Grade",
    stoneCut: "Polki",
    certification: "IGI",
    cadDesignRequired: false,
    advancePaid: 60000,
    totalEstimate: 210000,
    deliveryDate: daysFromToday(3),
    currentStage: "Certification",
    createdAt: isoTs(daysAgo(45)),
    lastUpdatedAt: isoTs(daysAgo(2)),
    activityFeed: [
      {
        id: "act-002-0",
        orderId: "ord-002",
        postedBy: "Dev R.",
        actorRole: "sales",
        timestamp: isoTs(daysAgo(45), "11:00:00"),
        type: "order_created",
        note:
          "Anniversary necklace order. ₹60,000 advance collected. Delivery needed by " +
          daysFromToday(3) +
          ".",
      },
      {
        id: "act-002-1",
        orderId: "ord-002",
        postedBy: "Dev R.",
        actorRole: "sales",
        timestamp: isoTs(daysAgo(45), "11:10:00"),
        type: "stage_change",
        previousStage: "Enquiry",
        newStage: "Order Confirmed",
        note: "Shared full specs with Sunrise Gold Works.",
      },
      {
        id: "act-002-2",
        orderId: "ord-002",
        postedBy: "Sunrise Gold Works",
        actorRole: "vendor",
        timestamp: isoTs(daysAgo(20), "09:30:00"),
        type: "stage_change",
        previousStage: "Order Confirmed",
        newStage: "Building",
        note: "All materials procured. Polki sourced from Jaipur. Starting work today.",
      },
      {
        id: "act-002-3",
        orderId: "ord-002",
        postedBy: "Dev R.",
        actorRole: "sales",
        timestamp: isoTs(daysAgo(12), "14:00:00"),
        type: "note",
        note: "Customer called to check status. Told him production is underway, on track for delivery.",
      },
      {
        id: "act-002-4",
        orderId: "ord-002",
        postedBy: "Sunrise Gold Works",
        actorRole: "vendor",
        timestamp: isoTs(daysAgo(7), "17:00:00"),
        type: "stage_change",
        previousStage: "Building",
        newStage: "Certification",
        note: "Piece completed and dispatched to IGI Andheri lab. Receipt attached.",
        file: {
          url: "/mock/igi-receipt-002.pdf",
          filename: "IGI-dispatch-receipt.pdf",
          fileType: "pdf",
        },
      },
      {
        id: "act-002-5",
        orderId: "ord-002",
        postedBy: "Dev R.",
        actorRole: "sales",
        timestamp: isoTs(daysAgo(2), "10:30:00"),
        type: "note",
        note:
          "Checked with IGI. Certificate will be ready in 2 days — should land with us by " +
          daysFromToday(1) +
          ".",
      },
    ],
  },

  // ── 3. DUE SOON (6 days) — Shipped to Store ──────────────────────────────
  {
    id: "ord-003",
    type: "order",
    orderNumber: "EVL-2026-003",
    shareableToken: "evl-003-deepa-bangles",
    customerName: "Deepa Nair",
    customerPhone: "+91 91234 77890",
    salespersonName: "Ananya S.",
    vendorName: "Heritage Crafts Mumbai",
    category: "Bangle",
    metalType: "Gold",
    metalPurity: "22K",
    metalWeight: 42,
    polish: "High polish",
    stoneDescription: "Ruby and Emerald",
    stoneQuality: "Good",
    stoneCut: "Cabochon",
    bangleSize: "2.6 inches",
    certification: "Jewellery",
    cadDesignRequired: false,
    advancePaid: 80000,
    totalEstimate: 310000,
    deliveryDate: daysFromToday(6),
    currentStage: "Shipped to Store",
    createdAt: isoTs(daysAgo(60)),
    lastUpdatedAt: isoTs(daysAgo(1)),
    specialInstructions:
      "Bridal set — handle with extra care. Customer collecting in person.",
    activityFeed: [
      {
        id: "act-003-0",
        orderId: "ord-003",
        postedBy: "Ananya S.",
        actorRole: "sales",
        timestamp: isoTs(daysAgo(60), "10:00:00"),
        type: "order_created",
        note:
          "Bridal bangles set — 2 pairs. ₹80,000 advance. Delivery " +
          daysFromToday(6) +
          ".",
      },
      {
        id: "act-003-1",
        orderId: "ord-003",
        postedBy: "Ananya S.",
        actorRole: "sales",
        timestamp: isoTs(daysAgo(60), "10:10:00"),
        type: "stage_change",
        previousStage: "Enquiry",
        newStage: "Order Confirmed",
        note: "Confirmed with Heritage Crafts. They've worked on similar bridal sets before.",
      },
      {
        id: "act-003-2",
        orderId: "ord-003",
        postedBy: "Heritage Crafts Mumbai",
        actorRole: "vendor",
        timestamp: isoTs(daysAgo(30), "09:00:00"),
        type: "stage_change",
        previousStage: "Order Confirmed",
        newStage: "Building",
        note: "Work has begun on both pairs. Ruby and emerald cabochons sourced.",
      },
      {
        id: "act-003-3",
        orderId: "ord-003",
        postedBy: "Heritage Crafts Mumbai",
        actorRole: "vendor",
        timestamp: isoTs(daysAgo(10), "16:00:00"),
        type: "file_upload",
        note: "Progress photo — stone setting complete on pair 1. Pair 2 in progress.",
        file: {
          url: "/mock/bangles-progress.jpg",
          filename: "bangles-pair1-progress.jpg",
          fileType: "image",
        },
      },
      {
        id: "act-003-4",
        orderId: "ord-003",
        postedBy: "Heritage Crafts Mumbai",
        actorRole: "vendor",
        timestamp: isoTs(daysAgo(3), "11:00:00"),
        type: "stage_change",
        previousStage: "Building",
        newStage: "Certification",
        note: "Both pairs completed. Sent for BIS hallmarking.",
      },
      {
        id: "act-003-5",
        orderId: "ord-003",
        postedBy: "Heritage Crafts Mumbai",
        actorRole: "vendor",
        timestamp: isoTs(daysAgo(1), "14:30:00"),
        type: "stage_change",
        previousStage: "Certification",
        newStage: "Shipped to Store",
        note: "Hallmarked and packed. Shipped via Blue Dart. AWB: BD-9821001234. Expected at store in 2 days.",
      },
    ],
  },

  // ── 4. ON TRACK — Building, 15 days away ──────────────────────────────────
  {
    id: "ord-004",
    type: "order",
    orderNumber: "EVL-2026-004",
    shareableToken: "evl-004-rahul-pendant",
    customerName: "Rahul Singhania",
    customerPhone: "+91 88001 44321",
    salespersonName: "Dev R.",
    vendorName: "Raj Jewel Craft",
    category: "Pendant",
    metalType: "White Gold",
    metalPurity: "18K",
    metalWeight: 3.1,
    polish: "High polish",
    stoneDescription: "Blue Sapphire",
    stoneQuality: "Eye-clean",
    stoneCut: "Oval",
    stoneCaratEstimate: 1.2,
    certification: "SGL",
    cadDesignRequired: true,
    advancePaid: 15000,
    totalEstimate: 55000,
    deliveryDate: daysFromToday(15),
    currentStage: "Building",
    createdAt: isoTs(daysAgo(20)),
    lastUpdatedAt: isoTs(daysAgo(3)),
    activityFeed: [
      {
        id: "act-004-0",
        orderId: "ord-004",
        postedBy: "Dev R.",
        actorRole: "sales",
        timestamp: isoTs(daysAgo(20), "12:00:00"),
        type: "order_created",
        note:
          "Birthday gift — white gold sapphire pendant. ₹15,000 advance. Deliver by " +
          daysFromToday(15) +
          ".",
      },
      {
        id: "act-004-1",
        orderId: "ord-004",
        postedBy: "Dev R.",
        actorRole: "sales",
        timestamp: isoTs(daysAgo(20), "12:10:00"),
        type: "stage_change",
        previousStage: "Enquiry",
        newStage: "Order Confirmed",
        note: "Sent brief to Raj Jewel Craft. CAD required — customer wants to approve design before production.",
      },
      {
        id: "act-004-2",
        orderId: "ord-004",
        postedBy: "Dev R.",
        actorRole: "sales",
        timestamp: isoTs(daysAgo(18), "09:00:00"),
        type: "stage_change",
        previousStage: "Order Confirmed",
        newStage: "CAD Design",
      },
      {
        id: "act-004-3",
        orderId: "ord-004",
        postedBy: "Raj Jewel Craft",
        actorRole: "vendor",
        timestamp: isoTs(daysAgo(12), "15:00:00"),
        type: "file_upload",
        note: "CAD design ready. 3D render attached. Sapphire setting is bezel-style as discussed.",
        file: {
          url: "/mock/cad-evl004.pdf",
          filename: "EVL-004-sapphire-pendant-CAD.pdf",
          fileType: "pdf",
        },
      },
      {
        id: "act-004-4",
        orderId: "ord-004",
        postedBy: "Dev R.",
        actorRole: "sales",
        timestamp: isoTs(daysAgo(10), "11:00:00"),
        type: "stage_change",
        previousStage: "CAD Design",
        newStage: "Building",
        note: "Rahul approved the design over phone. Confirmed bezel setting. Proceeding to manufacture.",
      },
      {
        id: "act-004-5",
        orderId: "ord-004",
        postedBy: "Raj Jewel Craft",
        actorRole: "vendor",
        timestamp: isoTs(daysAgo(3), "16:00:00"),
        type: "note",
        note: "Sapphire sourced and certified by SGL. Stone setting starts Monday. On track for delivery.",
      },
    ],
  },

  // ── 5. ON TRACK — Estimation ───────────────────────────────────────────────
  {
    id: "ord-005",
    type: "order",
    orderNumber: "EVL-2026-005",
    shareableToken: "evl-005-sunita-earrings",
    customerName: "Sunita Bose",
    customerPhone: "+91 97654 32100",
    customerEmail: "sunita.bose@yahoo.com",
    salespersonName: "Ananya S.",
    vendorName: "Sunrise Gold Works",
    category: "Earrings",
    metalType: "Gold",
    metalPurity: "18K",
    metalWeight: 5.8,
    polish: "High polish",
    stoneDescription: "Pink Tourmaline",
    stoneQuality: "VVS",
    stoneCut: "Pear",
    certification: "None",
    cadDesignRequired: false,
    advancePaid: 10000,
    totalEstimate: 38000,
    deliveryDate: daysFromToday(25),
    currentStage: "Estimation",
    createdAt: isoTs(daysAgo(5)),
    lastUpdatedAt: isoTs(daysAgo(1)),
    activityFeed: [
      {
        id: "act-005-0",
        orderId: "ord-005",
        postedBy: "Ananya S.",
        actorRole: "sales",
        timestamp: isoTs(daysAgo(5), "14:00:00"),
        type: "order_created",
        note:
          "Drop earrings with pink tourmaline. ₹10,000 advance. Customer needs these for a gala on " +
          daysFromToday(25) +
          ".",
      },
      {
        id: "act-005-1",
        orderId: "ord-005",
        postedBy: "Ananya S.",
        actorRole: "sales",
        timestamp: isoTs(daysAgo(4), "10:00:00"),
        type: "stage_change",
        previousStage: "Enquiry",
        newStage: "Estimation",
        note: "Sent specs to Sunrise Gold Works for quote. Waiting on stone availability confirmation.",
      },
      {
        id: "act-005-2",
        orderId: "ord-005",
        postedBy: "Sunrise Gold Works",
        actorRole: "vendor",
        timestamp: isoTs(daysAgo(1), "11:30:00"),
        type: "note",
        note: "Sourcing pear-cut pink tourmalines in VVS quality. Found two options — 1.8ct and 2.1ct per stone. Will confirm price for both and share estimate by tomorrow.",
      },
    ],
  },

  // ── 6. ON TRACK — Order Confirmed ─────────────────────────────────────────
  {
    id: "ord-006",
    type: "order",
    orderNumber: "EVL-2026-006",
    shareableToken: "evl-006-vijay-bracelet",
    customerName: "Vijay Tiwari",
    customerPhone: "+91 70000 99887",
    salespersonName: "Dev R.",
    vendorName: "Heritage Crafts Mumbai",
    category: "Bracelet",
    metalType: "Rose Gold",
    metalPurity: "18K",
    metalWeight: 8,
    polish: "Satin",
    stoneDescription: "Diamond tennis bracelet",
    stoneQuality: "SI1",
    stoneCut: "Round Brilliant",
    stoneCaratEstimate: 2.5,
    certification: "GIA",
    cadDesignRequired: false,
    advancePaid: 50000,
    totalEstimate: 175000,
    deliveryDate: daysFromToday(35),
    currentStage: "Order Confirmed",
    createdAt: isoTs(daysAgo(3)),
    lastUpdatedAt: isoTs(daysAgo(3)),
    specialInstructions:
      "GIA cert mandatory before delivery. Customer will not accept without it.",
    activityFeed: [
      {
        id: "act-006-0",
        orderId: "ord-006",
        postedBy: "Dev R.",
        actorRole: "sales",
        timestamp: isoTs(daysAgo(3), "15:00:00"),
        type: "order_created",
        note: "Rose gold diamond tennis bracelet. ₹50,000 advance. GIA cert mandatory.",
      },
      {
        id: "act-006-1",
        orderId: "ord-006",
        postedBy: "Dev R.",
        actorRole: "sales",
        timestamp: isoTs(daysAgo(3), "15:10:00"),
        type: "stage_change",
        previousStage: "Enquiry",
        newStage: "Order Confirmed",
        note: "Confirmed with Heritage Crafts. Shared full spec sheet.",
      },
    ],
  },

  // ── 7. ENQUIRY ─────────────────────────────────────────────────────────────
  {
    id: "enq-001",
    type: "enquiry",
    shareableToken: "enq-001-meera-chain",
    customerName: "Meera Pillai",
    customerPhone: "+91 94500 66123",
    salespersonName: "Ananya S.",
    category: "Chain",
    metalType: "Gold",
    metalPurity: "22K",
    polish: "High polish",
    certification: "None",
    cadDesignRequired: false,
    currentStage: "Enquiry",
    createdAt: isoTs(daysAgo(2)),
    lastUpdatedAt: isoTs(daysAgo(2)),
    budgetRange: "₹30,000 – ₹50,000",
    occasion: "Wedding gift",
    timelineNotes: "Needed within 3 weeks",
    activityFeed: [
      {
        id: "act-enq001-0",
        orderId: "enq-001",
        postedBy: "Ananya S.",
        actorRole: "sales",
        timestamp: isoTs(daysAgo(2), "12:30:00"),
        type: "order_created",
        note: "Walk-in enquiry. Interested in 22K gold chain, ~50–60cm length. Budget ₹30–50K. Wedding gift — needed within 3 weeks.",
      },
    ],
  },

  // ── 8. COMPLETE — Customer Pickup ─────────────────────────────────────────
  {
    id: "ord-007",
    type: "order",
    orderNumber: "EVL-2026-007",
    shareableToken: "evl-007-kavita-brooch",
    customerName: "Kavita Sharma",
    customerPhone: "+91 98100 77654",
    salespersonName: "Dev R.",
    vendorName: "Sunrise Gold Works",
    category: "Brooch",
    metalType: "Gold",
    metalPurity: "18K",
    metalWeight: 6.5,
    polish: "High polish",
    stoneDescription: "Emerald and Diamond",
    stoneQuality: "VS1",
    stoneCut: "Marquise",
    certification: "IGI",
    cadDesignRequired: false,
    advancePaid: 30000,
    totalEstimate: 95000,
    deliveryDate: daysFromToday(-10),
    currentStage: "Customer Pickup",
    createdAt: isoTs(daysAgo(50)),
    lastUpdatedAt: isoTs(daysAgo(10)),
    activityFeed: [
      {
        id: "act-007-0",
        orderId: "ord-007",
        postedBy: "Dev R.",
        actorRole: "sales",
        timestamp: isoTs(daysAgo(50), "10:00:00"),
        type: "order_created",
        note: "Antique-style brooch. ₹30,000 advance. IGI cert required.",
      },
      {
        id: "act-007-1",
        orderId: "ord-007",
        postedBy: "Dev R.",
        actorRole: "sales",
        timestamp: isoTs(daysAgo(50), "10:05:00"),
        type: "stage_change",
        previousStage: "Enquiry",
        newStage: "Order Confirmed",
        note: "Order placed with Sunrise Gold Works.",
      },
      {
        id: "act-007-2",
        orderId: "ord-007",
        postedBy: "Sunrise Gold Works",
        actorRole: "vendor",
        timestamp: isoTs(daysAgo(25), "09:00:00"),
        type: "stage_change",
        previousStage: "Order Confirmed",
        newStage: "Building",
        note: "Marquise emeralds and diamonds sourced. Starting work.",
      },
      {
        id: "act-007-3",
        orderId: "ord-007",
        postedBy: "Sunrise Gold Works",
        actorRole: "vendor",
        timestamp: isoTs(daysAgo(15), "16:00:00"),
        type: "stage_change",
        previousStage: "Building",
        newStage: "Certification",
        note: "Brooch completed. Sending to IGI for certification.",
      },
      {
        id: "act-007-4",
        orderId: "ord-007",
        postedBy: "Sunrise Gold Works",
        actorRole: "vendor",
        timestamp: isoTs(daysAgo(12), "11:00:00"),
        type: "stage_change",
        previousStage: "Certification",
        newStage: "Shipped to Store",
        note: "IGI certificate received (cert no. IGI-2026-00441). Piece shipped via hand delivery.",
      },
      {
        id: "act-007-5",
        orderId: "ord-007",
        postedBy: "Dev R.",
        actorRole: "sales",
        timestamp: isoTs(daysAgo(10), "14:00:00"),
        type: "stage_change",
        previousStage: "Shipped to Store",
        newStage: "Customer Pickup",
        note: "Kavita collected the piece. Balance of ₹65,000 received. Order complete.",
      },
    ],
  },
];

// ─── Lookup helpers ────────────────────────────────────────────────────────────

export function getOrderById(id: string): Order | undefined {
  return mockOrders.find((o) => o.id === id);
}

export function getOrderByToken(token: string): Order | undefined {
  return mockOrders.find((o) => o.shareableToken === token);
}
